version: "3.9"

networks:
  interlink:
    external: true

services:
  chat:
    image: ghcr.io/liukonen/riverscriptbackend:Main
    command: npm start
    environment:
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - DOMAIN=${BOTDOMAIN}
    ports:
    - 5005:5000
    restart: unless-stopped
    networks:
      - interlink
