version: '3.3'
services:
  web-alpine:
    build:
      context: .
      dockerfile: dockerfile
      labels:
      - "com.centurylinklabs.watchtower.enable=false"
    command: npm start
    environment:
      - npm_config_proxy=${npm_config_proxy}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - DOMAIN=${BOTDOMAIN}
    ports:
    - 5005:5000
    restart: unless-stopped
networks:
  existing-network:
    external:
      name: external