version: '3.3'
name: "RiveScript_Go"
services:
  web-alpine:
    build:
      context: .
      dockerfile: dockerfile
      labels:
      - "com.centurylinklabs.watchtower.enable=false"
    command: npm start
    ports:
    - 5055:5000
    restart: unless-stopped