version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
      labels:
      - "com.centurylinklabs.watchtower.enable=false"
    command: npm start
    ports:
    - 5005:5000
    restart: unless-stopped